---
name: test

on:
    push:
        branches:
        -   main
        -   master
    pull_request:
        branches:
        -   '*'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# Force to use color
env:
    FORCE_COLOR: true

jobs:

    test_python:
        # - minify jsavascript code and add it to python package
        # - run python tests via tox
        # - upload coverage as artifacts and to codecov

        name: Test with ${{ matrix.py }} on ${{ matrix.os }}

        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                py: ['3.13', '3.12', '3.11', '3.10']
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:

        -   uses: actions/checkout@v5

        -   uses: actions/setup-node@v4
            with:
                node-version: 18

        -   name: Minify JS for python
            run: make minify

        -   name: Install the latest version of uv
            uses: astral-sh/setup-uv@v6

        -   name: Setup python
            uses: actions/setup-python@v6
            with:
                python-version: ${{ matrix.py }}
                allow-prereleases: true

        -   name: Install tox
            run: uv tool install tox --with=tox-uv --with=tox-gh-actions
        -   name: Show tox config
            run: tox c

        -   name: Run test suite
            run: |
                tox run --list-dependencies -e test -- tests/python

        -   name: Upload html coverage
            if: success() || failure()
            uses: actions/upload-artifact@v4
            with:
                name: ${{ matrix.os }}_${{ matrix.py }}_htmlcov
                path: htmlcov

        -   name: Upload coverage to CodeCov
            uses: codecov/codecov-action@v5
            with:
                flags: ${{ matrix.os }}_${{ matrix.py }}
                token: ${{ secrets.CODECOV_TOKEN }}
            if: success()

    test_js:

        name: Test Javascript
        # - set up all js and python dependencies
        # - run js test with browser coverage
        #   - copy non-minified version of the code in python package (useful for coverage)
        #   - run python examples to generate html required by javascript tests
        # - upload coverage as artifacts

        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v5

        -   uses: actions/setup-node@v4
            with:
                node-version: 18

        -   name: Install the latest version of uv
            uses: astral-sh/setup-uv@v6

        -   name: Setup python
            uses: actions/setup-python@v6
            with:
                python-version: 3.10
                allow-prereleases: true

        -   name: Install tox
            run: uv tool install tox --with=tox-uv --with=tox-gh-actions

        -   name: Install
            run: npm install

        -   name: Run test suite
            run: make coverage

        -   name: Upload html coverage
            if: success() || failure()
            uses: actions/upload-artifact@v4
            with:
                name: coverage
                path: coverage

        -   name: Upload reference, new and diff images from test
            if: success() || failure()
            uses: actions/upload-artifact@v4
            with:
                name: image
                path: tests/js/*.png
